source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
workspace 'MediationExample.xcworkspace'

target 'SampleAdSDK' do
  project 'SampleAdSDK/SampleAdSDK.xcodeproj'
  pod 'Google-Mobile-Ads-SDK'
  pod 'GoogleMobileAdsMediationTestSuite'

  target 'SampleAdSDKAdapter' do
    inherit! :search_paths
  end

  target 'MediationExample' do
    project 'MediationExample.xcodeproj'
    pod 'VAMP'
    pod 'Google-Mobile-Ads-SDK'
    inherit! :search_paths
  end
end
